use terminus_store::storage::consts::FILENAMES;

pub const UNCHANGED_FILES: [&'static str; 30] = [
    FILENAMES.node_dictionary_blocks,
    FILENAMES.node_dictionary_offsets,
    FILENAMES.predicate_dictionary_blocks,
    FILENAMES.predicate_dictionary_offsets,
    FILENAMES.predicate_idmap_bits,
    FILENAMES.predicate_idmap_bit_index_blocks,
    FILENAMES.predicate_idmap_bit_index_sblocks,
    FILENAMES.parent,
    FILENAMES.pos_s_p_adjacency_list_nums,
    FILENAMES.pos_s_p_adjacency_list_bits,
    FILENAMES.pos_s_p_adjacency_list_bit_index_blocks,
    FILENAMES.pos_s_p_adjacency_list_bit_index_sblocks,
    FILENAMES.pos_sp_o_adjacency_list_bits,
    FILENAMES.pos_sp_o_adjacency_list_bit_index_blocks,
    FILENAMES.pos_sp_o_adjacency_list_bit_index_sblocks,
    FILENAMES.pos_predicate_wavelet_tree_bits,
    FILENAMES.pos_predicate_wavelet_tree_bit_index_blocks,
    FILENAMES.pos_predicate_wavelet_tree_bit_index_sblocks,
    FILENAMES.neg_s_p_adjacency_list_nums,
    FILENAMES.neg_s_p_adjacency_list_bits,
    FILENAMES.neg_s_p_adjacency_list_bit_index_blocks,
    FILENAMES.neg_s_p_adjacency_list_bit_index_sblocks,
    FILENAMES.neg_sp_o_adjacency_list_bits,
    FILENAMES.neg_sp_o_adjacency_list_bit_index_blocks,
    FILENAMES.neg_sp_o_adjacency_list_bit_index_sblocks,
    FILENAMES.neg_predicate_wavelet_tree_bits,
    FILENAMES.neg_predicate_wavelet_tree_bit_index_blocks,
    FILENAMES.neg_predicate_wavelet_tree_bit_index_sblocks,
    FILENAMES.pos_subjects,
    FILENAMES.neg_subjects,
];

pub const BASE_INDEX_FILES: [&'static str; 5] = [
    FILENAMES.pos_objects,
    FILENAMES.base_sp_o_adjacency_list_nums,
    FILENAMES.base_o_ps_adjacency_list_nums,
    FILENAMES.base_o_ps_adjacency_list_bit_index_blocks,
    FILENAMES.base_o_ps_adjacency_list_bit_index_sblocks,
];
pub const CHILD_INDEX_FILES: [&'static str; 10] = [
    FILENAMES.pos_objects,
    FILENAMES.neg_objects,
    FILENAMES.pos_sp_o_adjacency_list_nums,
    FILENAMES.neg_sp_o_adjacency_list_nums,
    FILENAMES.pos_o_ps_adjacency_list_nums,
    FILENAMES.pos_o_ps_adjacency_list_bit_index_blocks,
    FILENAMES.pos_o_ps_adjacency_list_bit_index_sblocks,
    FILENAMES.neg_o_ps_adjacency_list_nums,
    FILENAMES.neg_o_ps_adjacency_list_bit_index_blocks,
    FILENAMES.neg_o_ps_adjacency_list_bit_index_sblocks,
];
